### ISSUE TITLE
Asset (Image) uploading no longer working

### ISSUE THREAD

**Issue by Etheroit** [blake-mealey/mantle#235]
It seems that the `https://data.roblox.com/data/upload/json` endpoint got deprecated which made asset (images) uploading no longer working properly (getting 429 errors whenever trying to upload any image).

It seems that other tools also have migrated to Open Cloud solutions eg
https://github.com/Roblox/tarmac/commit/67797bf8a33e076194be455c3a4ddf4cf1ccb12d#diff-868d6f9c2d098b2dfb3456d2031f98ed2fcd5bc9a16a77a26691975b0e90bfb4L148

Happening on the most recent Mantle version.

![Image](https://github.com/user-attachments/assets/6639fe79-0a5a-4699-88d1-6f78cd8f0dea)

**Comment by blake-mealey** [comment]
Fixed in latest version: https://github.com/blake-mealey/mantle/releases/tag/v0.11.17

**Comment by Etheroit** [comment]
Hi @blake-mealey 
It appears that this is still not working as intended (it's being incorrectly uploaded as `Decal` and therefore when an asset alias is created it's being linked to id of a decal instead of id of an image and therefore does not work in studio as the asset alias). I suppose it should be uploaded as a image just like in tarmac case (there was an edit in one of the most recent commits).

**Comment by blake-mealey** [comment]
Just wanted to give you an update: I've been looking at this when I can find the time but it's proving more complicated than I expected. The library I use for open cloud APIs currently (rbx_cloud) does not support creating Images, only Decals. 

I also can't find docs for the "user auth" versions of the APIs which tarmac seems to be using, but it seems like I don't necessarily have to use Open Cloud: https://github.com/Roblox/tarmac/blob/master/src/roblox_web_api.rs#L167

**Comment by Etheroit** [comment]
@blake-mealey Ill look into it a little more to see what I can figure out. Isn't a simple value swap `type = if type == "Decal" then "Image" else type` sufficient? (Right now you seem to use rbx_cloud function to resolve type from extension)

I believe rbx_cloud uses the same api as tarmac and if you provided "Image", itd just upload it as the image (?) [I believe there are no additional checks inside but I might be wrong]

**Comment by blake-mealey** [comment]
Yup that's correct, however rbxcloud uses a custom AssetType enum which doesn't allow setting the type to Image. I made some progress last night adding support to rbx_api.

**Comment by Etheroit** [comment]
@blake-mealey Fair enough. Enum indeed complicates a lot.

**Comment by blake-mealey** [comment]
This should be fixed in https://github.com/blake-mealey/mantle/releases/tag/v0.11.18

**Comment by Etheroit** [comment]
@blake-mealey Tysm and apologies for the hassle. I really need to learn rust lol - so unfortunate nobody takes over the project maintenance as I can imagine you're now working on other stuff @ vercel :)
